### ISSUE TITLE
iOS app crashes when using IODispatcher

### ISSUE THREAD

**Issue by belousovgm** [Autodesk/coroutineworker#82]
When I trying to run this code:

```
GlobalScope.launch {
    CoroutineWorker.withContext(Dispatchers.IO) {
         while (true) {
             delay(15)
         }
    }
}
```

approximately on 10-15th loop iteration iOS app crashes.

Kotlin: 1.4.31
coroutineworker: 0.6.2

Actual implementation of Dispatchers.IO:
```
actual val Dispatchers.IO: CoroutineDispatcher
    get() = IODispatcher
```

**Comment by benasher44** [comment]
Hi thanks for the report! What version of kotlinx.coroutines are you using?

**Comment by belousovgm** [comment]
1.4.2-native-mt

**Comment by benasher44** [comment]
Ah okay thanks for providing that. CoroutineWorker is meant to be used instead of the native-mt branch. It provides multi-threaded coroutine capabilities in an environment without native-mt. One day when native-mt is merged to main/master coroutines, this library will be no longer needed for example. 

For your use case and with native-mt generally, you should use kotlinx.coroutines-provide primitives/methods—don't use CoroutineWorker, as the two are not designed to work together. In this particular case, you probably want to make your own global single-threaded dispatcher to use as an IO dispatcher and use the kotlinx.coroutines withContext method with that dispatcher here.

Going to close, as it's expected that native-mt is not designed to work with CoroutineWorker—in fact it will obsolete it one day. Thanks again for flagging!
